### ISSUE TITLE
Issue with calibre web db

### ISSUE THREAD

**Issue by shubhank-saxena** [abhilesh/self-hosted_docker_setups#1]
Thank you so much for this amazing collection of docker-compose files!
While firing up calibre-web I am not able to locate the correct location of DB. Can you please help me out with that?
This is my docker-compose
```
version: "2.1"
services:
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      # I had some issues with Google's OAuth login and hence added the following two lines
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - OAUTHLIB_INSECURE_TRANSPORT=1
    volumes:
      - /srv/dev-disk-by-label-media/Files/AppData/Config/Calibre-Web:/config                   # Config directory (`app.db` is stored here)
      - /home/dietpi/Documents/Library:/books            # Data directory (All ebooks are stored here)
    ports:
      - 8083:8083
    restart: unless-stopped
```
